services:
  # API Service
  api:
    build:
      context: .
      target: dev
    container_name: github-repo-scoring-api-dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
      GITHUB_API_BASE_URL: https://api.github.com
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm run start:dev"
    volumes:
      - ./:/app
      - /app/node_modules
